name: Generate Dog Contribution Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate Dog SVG
        uses: Platane/snk@v3
        with:
          github_user_name: dhairyamittal28106-alt
          outputs: |
            dist/dog.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update dog contribution animation"
          add: "dist/dog.svg"
